/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mattman' at '5/27/16 3:43 PM' with Gradle 2.13
 *
 * @author mattman, @date 5/27/16 3:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
